- hosts: all
  tasks:
    - name: Copy the artifact
      copy:
        src: main
        dest: /home/laborant/main
        mode: '0755'

    - name: Create a unit file
      become: True
      copy:
        src: myapp.service
        dest: /etc/systemd/system/myapp.service

    - name: Enable and start myapp service
      become: True
      systemd:
        name: myapp.service
        daemon_reload: yes
        enabled: yes
        state: restarted